# Generated by Django 6.0.4 on 2026-04-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Tools', 'Tools'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Other', 'Other')], default='Other', max_length=50)),
                ('daily_rate', models.PositiveIntegerField(help_text='Price per day in ₹')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('available', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
